### PR TITLE
Add Netflix strategy

### LINKED ISSUE #61: App Support - Netflix

### PR DESCRIPTION
**Pull request by fmborghino**
- implemented toggle, pause, isPlaying, track info title
- site does not support: fav, track artist, track art
- skip forward and back probably possible but requires sending key press events
- fixes #61, replaces PR #126, thanks @martijnengler for the start

### CODE REVIEW

**Comment by Stillness-2** [comment]
Come on already :)

**Comment by Stillness-2** [comment]
@fmborghino can you merge into master?

**Comment by fmborghino** [comment]
Whoa yeah. Thanks!

Did you think Netflix was not a good fit for beardedspice? Those last two PRs were not vanilla music players, but they do benefit a lot from the media key hookup.

Thinking of Audible next, as I use that too :)

**Comment by Stillness-2** [comment]
:) If you plan create new PRs or resolve issues, then do not forget to assign them to "milestone" and "assignee".

**Comment by fmborghino** [comment]
Ah hah I see. I've never done that before - I'll try it with Audible. Thanks for the pointers!

**Pull request merged**
