### PR TITLE
added support for pakartot.lt

### PR DESCRIPTION
**Pull request by monai**

### CODE REVIEW

**Comment by Stillness-2** [comment]
Please add methods: 
trackInfo
favorite

**Comment by monai** [comment]
Added `favorite` and `trackInfo` methods.

**Comment by 1ps0** [comment]
Needs updating against the new JS template.

**Comment by 1ps0** [comment]
@monai Converted and committed. If you're running the latest Bearded Spice version (or anything at or past 2.0) you can run Compatibility Updates to download the strategy. Thanks for waiting :)

**Pull request closed without merging**
