### PR TITLE
Add Watcha Play Strategy

### PR DESCRIPTION
**Pull request by Reevid**

### CODE REVIEW

**Comment by Reevid** [comment]
It looks like only validate in South Korea

No one lives in Korea? Except me

**Comment by fmborghino** [comment]
OK! I signed up for a free trial VPN service, and fumbled through making an account (I can't read anything on the site but I figured it out :)  )

Everything works great except a small bug in your css selector for the title, the element has both the classes on it, so you need to get rid of the space in the selector. So like this:

```
var track=document.querySelector('.vjs-title-display.vjs-display');\
```

Or just keep it more simple, and use just the one selector, as the result is still unique:

```
var track=document.querySelector('.vjs-title-display');\
```

If you can fix that pretty quick, I can retest it. My trial VPN account lasts for 3 days only :-)

Nice work!

**Comment by fmborghino** [comment]
Oh also don't forget to rebase on the current master. 

Here's a branch with the change and rebase if you want a reference https://github.com/fmborghino/beardedspice/tree/Reevid-master

**Comment by Reevid** [comment]
I Changed my Code, but I don't know how to rebase on the current master

Can you give me a advice about rebase?

**Comment by fmborghino** [comment]
Hey Reevid, thanks for the change. For resolving the conflicts, there are a couple of options:

- take a look at the instructions right on this page there it says "Use the command line to resolve conflicts..."
- if you get stuck with this, I can grab your branch, fix the conflicts and push it from there - I *think* this will show up as your change with my help - I think it'll say `Reevid committed with fmborghino` - not sure because I have not tried this before

**Comment by Coder-256** [comment]
@fmborghino @Reevid Or just do:

```
git stash save
git pull <remote>
git stash pop
```

`<remote>` is probably `beardedspice`, but not `origin`.

**Comment by fmborghino** [comment]
Oops. Clicked close by accident!

**Comment by fmborghino** [comment]
@Reevid I rebased your PR (which resolves the conflicts and allows a merge), and squashed (an optional step which collapses the 5 commits into one, which makes the change easier to read) and re-tested (another 3 day free account on a VPN!). Everything works great.

You can see what this looks like in the last commit on this branch: 

https://github.com/fmborghino/beardedspice/commits/Reevid-master

If you are not sure how to rebase *your* branch I can commit this one. It will show up as `Reevid committed with fmborghino ` so you'll still be the main committer (I am pretty sure that's how it'll show up - I've never worked on someone else's branch and then merged it!). Let me know if you want me to do that, else I'll leave your PR alone until you come back to it.

**Comment by Reevid** [comment]
@fmborghino Thank you. I hope you do that instead of me :D

still I'm not used to rebase somthing

**Comment by fmborghino** [comment]
Done, thanks!

**Comment by Reevid** [comment]
Thank You :D

**Pull request closed without merging**
