### PR TITLE
Add PocketCastsBeta media strategy

### LINKED ISSUE #725: [App Support] Pocket Casts Beta Player
I just noticed that Pocket Casts has a new beta player on the web. I guess this will take over the current player, so an update might be necessary even if the beta player should not be supported.

https://playbeta.pocketcasts.com/web/

### PR DESCRIPTION
**Pull request by filoxo**
Resolves #725. I'd imagine that once the player is out of beta this strategy could be merged into the `PocketCasts` strategy.

### CODE REVIEW

**Comment by filoxo** [comment]
Oops, I guess this PR only partially resolves 725 as it only enables the web player, not the native app.

**Comment by filoxo** [comment]
Oh looks like I missed that 725 also requests support for the desktop app, so this PR only partially resolves that one (unless the native app support is something that the project isn't willing to do).

**Comment by Arro** [comment]
Can this be merged? I want this.

**Comment by Stillness-2** [comment]
@aray you can use export/import functions in preferences. Create text file with `.bsstrategy` extension. Copy script from this PR into it and import in BS.

**Comment by filoxo** [comment]
Should I close this PR? PocketCast's long-lived beta status makes me feel like this should just be merged, and once PocketCasts is out of beta, then this should be fixed forward.

**Comment by filoxo** [comment]
Someone else can cherry pick my changes if they'd like to include them in their own PR. I'm closing this due to lack of activity.

**Pull request closed without merging**
