### PR TITLE
Provide strategy for Laracasts

### PR DESCRIPTION
**Pull request by nVitius**
This is an updated strategy for one that was proposed but never merged in https://github.com/beardedspice/beardedspice/pull/182

### CODE REVIEW

**Comment by nVitius** [comment]
@1ps0: I've confirmed that this works by importing it into my local installation of BS (v2.2.2) on Chrome 58 and testing it on the site.

**Comment by 1ps0** [comment]
I'm having trouble testing this without a paid account. Is there a way around it?

**Comment by nVitius** [comment]
@1ps0 I don't have an account either. I just picked a random video. For example: https://laracasts.com/series/object-oriented-bootcamp-in-php/episodes/1

**Comment by 1ps0** [comment]
That one is great. None of the random ones I chose were loading properly. Have this merged shortly.

**Pull request merged**
