### PR TITLE
Add Cozy Cloud Music app support

### PR DESCRIPTION
**Pull request by CPatchane**
Add the support of the Music application of Cozy Cloud ([more about cozy-music](https://github.com/cozy-labs/cozy-music)).

### CODE REVIEW

**Comment by 1ps0** [comment]
Love the concept of this site. PR pending being able to test it. :)

**Comment by CPatchane** [comment]
Some news about this PR?

**Comment by 1ps0** [comment]
err. I missed my window for this. Talking with support.

**Comment by 1ps0** [comment]
@CPatchane took a bit more effort but got my instance back. Tested and deployed. Run the compatibility update and check it out :)

**Comment by CPatchane** [comment]
Great! Thanks @1ps0

**Pull request merged**
