### PR TITLE
Use latest queries in strategy for HypeMachine

### LINKED ISSUE #657: Hype Machine broken
Hello,

It's been a while since I haven't been on [Hype Machine](http://hypem.com) but BS doesn't seem to map any command anymore.

- macOS 10.12.4
- Google Chrome 58.0
- BS 2.2.2

Thanks,

### PR DESCRIPTION
**Pull request by nVitius**
This fixes #657

### CODE REVIEW

**Comment by nVitius** [comment]
@1ps0: I've confirmed that this works by importing it into my local installation of BS (v2.2.2) on Chrome 58 and testing it on the site.

**Comment by Stillness-2** [comment]
@nVitius What about `trackInfo`?

**Comment by nVitius** [comment]
@Stillness-2 I confirmed that one still works as-is.

**Comment by 1ps0** [comment]
@nVitius can you verify that 2.2.3 fixed this issue? I'd rather keep direct js calls than indirect ui element events.

**Comment by nVitius** [comment]
@1ps0 It does indeed work on 2.2.3. That's really odd though, as I remember testing the commands directly in the JS console in Chrome and they didn't work...

**Comment by 1ps0** [comment]
It's because Google broke Chrome for a workaround that we normally used, then fixed it in a patch about a week after I released 2.2.2 (about 2-3 months after it broke). The irony is amazing.

**Pull request closed without merging**
