### PR TITLE
Adds support for Downcast (Mac OS)

### PR DESCRIPTION
**Pull request by gcox**
#355 

~~An update for Downcast which adds the required AppleScript support for this is currently awaiting review in the Mac App Store (submitted on 8/7/16).~~ The most recent version of [Downcast (v2.9.16)](https://itunes.apple.com/us/app/downcast/id668429425?mt=12) contains the required AppleScript support.

### CODE REVIEW

**Comment by gcox** [comment]
If a Downcast promo code is needed in order to get this merged, please let me know.

**Comment by 1ps0** [comment]
It would help. Send one to my email, it's in the commit logs :)

**Comment by Stillness-2** [comment]
Hello @gcox 
I am trying to develop BeardedSpice on a fork of Beardie :)
https://github.com/Stillness-2/beardie

At the moment, I check and restore adapters and strategies to a working state.
Checking the Downcast adapter found that rewinding to the next/previous track (podcast episode) is not very suitable for a podcast player. I decided to do it like this:
```
- (BOOL)next{
    DowncastApplication *downcast = self.downcast;
    if (downcast) {
        DowncastNowPlayingInfo *npi = downcast.nowPlayingInfo;
        NSInteger newPosition = npi.playPosition + F_SEEK;
        if (newPosition > npi.duration) {
            newPosition = npi.duration;
        }
        [npi setPlayPosition:newPosition];
        return YES;
    }
    return NO;
}
```
Found that it does not work :) On my test, `duration` is always equal ` playPosition`, and setting a new value for `playPosition` does not work.
Can you fixed the `AppleScript` support in` Downcast` for this case? :)

**Comment by gcox** [comment]
@Stillness-2 Thanks for reporting this. There are a couple of issues here. 

Thanks for reporting the issue about the duration & play position always matching, that is definitely a bug and it will be fixed in the next release later this week.

Downcast's now playing info is intentionally readonly. In Downcast's iOS app, there is a setting for controlling what happens when the next/previous remote commands are received. Users can choose to have it skip to the next/previous episode **or** they can have it skip forward/backward by an interval that is configurable within the app. That particular setting doesn't yet exist in the macOS app, but it will in the very near future. The scriptable next/previous commands will honor that setting when it is added. Therefore, there's no need to change Downcast's `NativeAppTabAdapter` implementation.

**Pull request merged**
