### PR TITLE
Added Subsonic (http://subsonic.org/) and TuneIn (http://tunein.com/) media strategies.

### PR DESCRIPTION
**Pull request by CampinCarl**
Added a media strategy for the Subsonic Personal Media Streamer (http://subsonic.org/) application.

The predicate for the strategy is based off of the tab's title. This introduces a possible source of confusion since subsonic.org and the user's Subsonic deployment share that title. However, it works well for me in my testing.

### CODE REVIEW

**Comment by foozee** [comment]
Thanks for the PR, Would be great if you could implement the `trackInfo` method too.
And `favorite` of subsonic supports that :) no pressure, but would be great if u had time to do them while we review a couple of other PRs ;)

**Comment by CampinCarl** [comment]
Okay, I've got the trackInfo (including album art) and favorite methods implemented. Any recommendation on the size of the album art that should be used? The full size art seems to slow down the notifications. I can specify a size in my URL and I'm currently testing using 50 pixels (which seems to be working well enough).

Do I need to submit a new pull request or will this one update automatically once I commit the code?

**Comment by CampinCarl** [comment]
Found a [blog post](http://blog.timschroeder.net/2014/01/25/os-x-notifications-with-custom-images/) that suggests that the size is limited to 44x44 pixels. Going with that for now.

**Comment by foozee** [comment]
Thanks :) as you can see, any further commits you do to your branch are automatically reflected in the PR, thanks to the awesome magic of GitHub :D

**Comment by CampinCarl** [comment]
Very cool! Well, that's it for now. Let me know if it needs anything else or if you have any advice.

Thanks for your help!

**Comment by foozee** [comment]
Thanks, cheers and congratZ on the first commit, please keep it up :) we'll leave that here till I or @Stillness-2 get a chance to download subsonic and test and merge this for release 1.1 

Thanks again

**Comment by Stillness-2** [comment]
@CampinCarl images can be 128x128 - 44-44 pixels, but will be better if 128x128 :)

**Comment by Stillness-2** [comment]
wrong button pressed :)))

**Comment by CampinCarl** [comment]
Okay, I'll modify the build to switch to 44 instead of 128.

**Comment by CampinCarl** [comment]
Done!

**Comment by CampinCarl** [comment]
Added TuneIn to the pull request.

**Comment by CampinCarl** [comment]
I'm having problems getting this back into sync with the newest version. I'm going to attempt to re-baseline my fork and re-add the TuneIn and Subsonic strategies that way.

**Comment by CampinCarl** [comment]
Issues resolved under a new repo. I'll open a new request.

**Pull request closed without merging**
