### PR TITLE
Improve YouTubue strategy

### PR DESCRIPTION
**Pull request by vmfhrmfoaj**
Support to jump(seek) to previous or next for the video that combines multiple videos with the time table.
sample: https://www.youtube.com/watch?v=pwqVL0m-VUs

I agree that in normal case, the feature(seek) is unnecessary.

Thank.

### CODE REVIEW

**Comment by 1ps0** [comment]
Hey. Apologies for the late response.

This is a great step forward and definitely something we need. I've been talking with a couple others in #555 about a more formal way to video skipping. If you want, maybe we can pull out the skip forward/backward functions and put them in their own template functions. I'm thinking `skip_forward` and `skip_backward`. 

Thoughts?

**Comment by vmfhrmfoaj** [comment]
I found @beardedspice support to import the strategy.
It helps to customize, Thank.
So, I had closed the pull request.
- [My Custom Youtube strategy](https://gitlab.com/snippets/35404); Support to jump forward and backward a song in playlist of combined video.

Here, I pull out the function.

**Plus 5 sec**:
```javascript
skip_forward: function () {
  var skip = 5;
  var player = document.querySelector("#movie_player");
  yt.www.watch.player.seekTo(Math.min(player.getCurrentTime() + skip, player.getDuration()));
}
```
for test:
```javascript
(function () {
    var skip = 5;
    var player = document.querySelector("#movie_player");
    console.log("before: ", player.getCurrentTime());
    yt.www.watch.player.seekTo(Math.min(player.getCurrentTime() + skip, player.getDuration()));
    console.log("after: ", player.getCurrentTime());
  })();
```

**Minus 5 sec**:
```javascript
skip_backward: function () {
  var skip = 5;
  var player = document.querySelector("#movie_player");
  yt.www.watch.player.seekTo(Math.max(player.getCurrentTime() - skip, 0));
}
```
for test:
```javascript
(function () {
    var skip = 5;
    var player = document.querySelector("#movie_player");
    console.log("before: ", player.getCurrentTime());
    yt.www.watch.player.seekTo(Math.max(player.getCurrentTime() - skip, 0));
    console.log("after: ", player.getCurrentTime());
  })();
```

Thanks.

**Comment by jdamour98** [comment]
The attached file is no longer working for me. It did for several monthes, then failed recently. Macbook Pro, macOS 10.13, Safari Version 11.0, BeardedSpice 2.2.3

**Comment by vmfhrmfoaj** [comment]
Hi @jdamour98,

You can download and import [my custom strategy](https://gitlab.com/snippets/35404) for YouTube.
This version work well.

**Comment by patrickrushton** [comment]
The custom strategy doesn't work for me. But I was able to modify the default Youtube strategy and paste in the contents of your skip_backward and skip_forward functions to get the functionality I wanted (have the media keys seek 5s rather than skip to the prev/next video).

**Pull request closed without merging**
