### PR TITLE
Fix Yandex.Radio strategy

### PR DESCRIPTION
**Pull request by mokcrimea**

### CODE REVIEW

**Comment by veged** [comment]
can you do this for Yandex.Music too?

**Comment by 1ps0** [comment]
Please increment the version number in the YandexRadio.js strategy and it's entry in the  versions.plist file.

**Comment by mokcrimea** [comment]
@1ps0 fixed

Also added fix for Yandex.Music  /cc @veged

**Comment by veged** [comment]
:+1:

**Comment by 1ps0** [comment]
All set. Thanks for your hard work :)

**Pull request merged**
