### PR TITLE
Update Udemy MediaStrategy for Late 2016

### PR DESCRIPTION
**Pull request by nelsonjchen**
* Replaced Previous and Next - The "Previous" lecture button is now
    missing and while "Next" lecture could still be implemented, I opted to
    replace the functionality. I made "Next" scrub forward 15 seconds
    and "Previous" scrub backwards 15 seconds as in the GUI.

* Updated the selectors to handle the newer non-iFrame Angular UI.

### CODE REVIEW

**Comment by nelsonjchen** [comment]
This might close #372.

**Comment by 1ps0** [comment]
You wouldn't happen to have a link to something free I can test on? All the existing links i'm finding are black friday prices ($15).

**Comment by nelsonjchen** [comment]
There's a code that can get the price down to $10, `CNETBF2016`, but even that's not free. It also, like black friday, will expire at the end of the night. Anyway, that's just an FYI. 

As for the free courses, they're not on the front page at the moment. You have to go into the categories on the left menu. At the [IT and software section](https://www.udemy.com/courses/it-and-software/other/), there are a bunch of free courses right above the fold. Here's [one example from there](https://www.udemy.com/aws-concepts/) that can be used. As far as I can see, my approach also work there too. 

If testing on a paid @udemy course is really desired, perhaps they can donate access to one. *shrug*. But as far as I can tell, the viewer on the free courses do not look to be any different from the paid courses.

They do have a `Start Preview` option on a paid course. You can probably use that on something like [this meh course](https://www.udemy.com/refactoru-intro-unit-test/). It does result in an extra element topbar at the top being but it's pretty close to paid.

screen shot 2016-11-25 at 6 16 25 pm

I can say that my approach also appears to work on those as well.

**Comment by 1ps0** [comment]
Awesome, best answer ever. Tested and merged. If you dont have it loaded just run Compatibility Updates. Cheers!

**Pull request merged**
