### PR TITLE
Updated Stingray strategy

### PR DESCRIPTION
**Pull request by jmcouillard**
Fixed Stingray strategy with new website DOM changes.

### CODE REVIEW

**Comment by 1ps0** [comment]
Don't forget to toss your name in the copyright :D

`// Updated by ... on ...`

**Comment by jmcouillard** [comment]
Should I close this pull request and open a new one with the updated comments ?

**Comment by 1ps0** [comment]
Nah, any extra commits you add will be included in the PR. Go for it.

**Comment by 1ps0** [comment]
You're all set. Thanks :)

**Pull request closed without merging**
