### PR TITLE
Issue 805 add youtube music

### PR DESCRIPTION
**Pull request by andreaswilli**
Updates #819 which adds support for YouTube Music #805 (thanks @gapurov).
Renames `Youtube` to `YouTube` to have consistent naming.

### CODE REVIEW

**Comment by gapurov** [comment]
@andreaswilli thanks

**Comment by andreaswilli** [comment]
So, who can get this merged?

**Comment by jordyvandomselaar** [comment]
Bump! Would love youtube music support.

**Comment by xorik** [comment]
Guys, you could import and use it before it released, just save and import these 2 files:

https://raw.githubusercontent.com/beardedspice/beardedspice/fd295433be471fbf04326ec76105da75725e7d6f/BeardedSpice/MediaStrategies/Youtube.js
https://raw.githubusercontent.com/beardedspice/beardedspice/fd295433be471fbf04326ec76105da75725e7d6f/BeardedSpice/MediaStrategies/YoutubeMusic.js

**Comment by andreaswilli** [comment]
@xorik Right, that's what I've been doing. Would still be nice to have this out of the box.

**Comment by Stillness-2** [comment]
added to [BS-Strategies](https://github.com/beardedspice/BS-Strategies)

**Comment by epk** [comment]
> added to [BS-Strategies](https://github.com/beardedspice/BS-Strategies)

It does not help much as it is still a painful manual step which can't be automated. What would you require to package this strategy with the application?

**Comment by Stillness-2** [comment]
@epk read this #899, if still not

**Comment by epk** [comment]
> @epk read this #899, if still not

I have read that and that’s why I specially asked 

> What would you require to package this strategy with the application?

I am open to fulfilling the requirements you might have

**Pull request merged**
