### PR TITLE
Improved Synology Audiostation detection.

### PR DESCRIPTION
**Pull request by jhuebsch**
Changed detection script to make sure the baseurl check doesn't cause errors on sites that do not have it set. Fixing https://github.com/beardedspice/beardedspice/issues/637

### CODE REVIEW

**Comment by 1ps0** [comment]
It still fails for me on a demo instance.

**Comment by jhuebsch** [comment]
I'm not experiencing any issues controlling on the live demo site using chrome or safari. The only code I changed was the detection. 

Could you describe your issue more and I'll try and figure out what's going on.

**Comment by 1ps0** [comment]
I'm actually thinking this is systemic for me. I was having issues calling up `baseURL`, but I'm also getting the CSP error on just about every page i try to test. This is all taking more time to debug than I can afford.

Can I get some +1s for those who've verified it works for them?

**Comment by 1ps0** [comment]
My tests are getting blocked by Chrome 58. After I fix that I'll give this another whirl.

**Pull request merged**
