### PR TITLE
Update GoogleMusicStrategy.m

### PR DESCRIPTION
**Pull request by scott113341**
Looks like they changed their layout today #159

### CODE REVIEW

**Comment by falsefalse** [comment]
:+1: 
Come on come on come on, this begs for merging and subsequently for a new release :)

**Comment by foozee** [comment]
hey @scott113341  and @falsefalse  first am sorry about the delayed response, seems both of me and @Stillness-2  were a little bit busy ... 
we'll be releasing an update with this fix within the next two days

thanks @scott113341 for the fix

**Comment by falsefalse** [comment]
:+1:

**Comment by tbaron** [comment]
:ship:

**Comment by scott113341** [comment]
Hahaha no worries @foozee

**Pull request merged**
