### PR TITLE
Fixed wonderfm controls, added prev-track functionality

### PR DESCRIPTION
**Pull request by wiffbi**
Due to a wonderfm-update needed to update CSS-selectors and use dispatchEvent

Info: I tried to refactor dispatchEvent into a local function inside a closure
doing an iife worked (at least it returned the object), but did not create a closure

### CODE REVIEW

**Comment by 1ps0** [comment]
Great job! Tested and ready to go, but first...

1. Increment the version number in the `.js` and `versions.plist`
2. Fix the comment header to be `WonderFM.js` instead of `.plist` (its been bugging me a while)
3. Update the copyright to be `//  Copyright (c) 2016 GPL v3 http://www.gnu.org/licenses/gpl.html` since you've essentially rewritten the whole thing. 

Thanks!

**Comment by wiffbi** [comment]
@1ps0 thanks for the quick reply. I pushed all the changes you mentioned!

On thing: I don’t know about WonderFM.js, line 6: "Edited  by Richard Schreiber on 12/18/16" – that is me, but I actually do not mind, it not being in there. Feel free to remove that line.

Btw.: thanks for this awesome application!

**Comment by 1ps0** [comment]
haha nono leave that in. I was just looking to update the license to be in line with the rest of the app (from the original guys who used the default to a more open source friendly GPL3 :) I definitely want you to get credit where credit is due.

Much appreciated, I'll get it merged in shortly.

**Comment by 1ps0** [comment]
You're good to go. Run compatibility updates (if you havent already installed it) to download and install it officially. 
Thanks!

**Pull request merged**
