### PR TITLE
Adding support for Safari Technology Preview

### PR DESCRIPTION
**Pull request by mermaid**
Safari Technology Preview can now be supported in a similar way to all the different chrome instances. I just did basically the same thing. Got the app by the bundle identifier, made sure it got refreshed... Did have to change addSafariStatusMenuItemFor to accept the application since you can now pass in normal Safari or Safari TP

Related to bug #368

### CODE REVIEW

**Comment by mermaid** [comment]
Build seems have to failed because of #400

**Comment by nathantschultz** [comment]
Any updates on this?

**Comment by saagarjha** [comment]
I'd like to see this merged in as well.

**Comment by AnthonyWhitakerJr** [comment]
Retested these changes against Travis in #542 and the build passed.

**Comment by 1ps0** [comment]
This is up with [2.2.0-b1 prerelease](https://github.com/beardedspice/beardedspice/releases/tag/v2.2.0-b1) now.

**Pull request merged**
