### PR TITLE
Update Audiomack strategy

### PR DESCRIPTION
**Pull request by okcoker**
The Audiomack site had a big redesign. There will be an exposed version of the player for BS in the next deploy.

### CODE REVIEW

**Comment by 1ps0** [comment]
Hey! Thanks for doing this (and apologies for taking so long to respond).

A couple things real quick while I test.

1. You basically rewrote the whole strategy, so please feel free to add your name to the copyright. It could look something like 
```
//  Created by You on Today's Date.
//  Copyright (c) 2017 GPL v3 http://www.gnu.org/licenses/gpl.html
```

2. Can you update the version number for `Audiomack` in the [versions.plist](https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/MediaStrategies/versions.plist) file?

Thanks!

**Comment by okcoker** [comment]
@1ps0 No worries! Updated things now. I don't think fixing the casing should present any problems right?

**Comment by 1ps0** [comment]
One last thing, pretty big but an easy fix. Can you `git mv Audiomack.js AudioMack.js`. Turns out its creating an entirely new strategy (by file namespace) that conflicts with the old one. I can handle it if you just wanna push it out :)

**Comment by okcoker** [comment]
@1ps0 Ok no problem. Just pushed that change

**Comment by 1ps0** [comment]
All set. Thanks, and thanks for your patience :)

**Pull request merged**
