### PR TITLE
Added Gaana and Poolside FM Strategies.

### LINKED ISSUE #425: [App Support] gaana.com support
Please see if you can support gaana.com

Thanks

### PR DESCRIPTION
**Pull request by Coder-256**
Fixes #425. I had trouble building (I think it is caused by an internal problem with CocoaPods, which I have had trouble with before), but tests in browser worked fine.

### CODE REVIEW

**Comment by 1ps0** [comment]
Get this merged in as soon as we wrap up the js-conversions branch (so close).

**Comment by Coder-256** [comment]
@1ps0 I assume it worked then?

**Comment by 1ps0** [comment]
Works, yea. Thankfully that site doesn't require an account much less payment to use.

**Comment by Coder-256** [comment]
I also added Poolside FM for #428. Same situation with the build.

**Comment by 1ps0** [comment]
Please sync against master.

**Comment by Coder-256** [comment]
I thought that accepting a PR just applies the diff, but done anyways.

**Comment by 1ps0** [comment]
If only it was that nice. It's close, but whenever you have diverging branches, it's up to the individual owners to sync then push. Otherwise I have to sort out what you added and what we want to keep.

**Comment by 1ps0** [comment]
Merged

**Pull request closed without merging**
