### PR TITLE
Add Pluralsight strategy

### PR DESCRIPTION
**Pull request by alt3red**
Added strategy for the learning platform https://www.pluralsight.com . I had to recreate this branch because of another strategy that needed removing and was added to it's own branch and merged.

### CODE REVIEW

**Comment by 1ps0** [comment]
@alt3red lol. third times the charm?

**Comment by alt3red** [comment]
I think I am doing something wrong because the tests keep failing now. So I need to take a break and revisit with a clear head lol.

**Comment by 1ps0** [comment]
Dont worry about the tests. They break randomly. They're mostly to provide a sanity check for the bare minimum JS in a new strategy. Working towards testing your strategy now :)

**Comment by 1ps0** [comment]
@alt3red also looks like them breaking is my fault. :headpat:

**Pull request closed without merging**
