### PR TITLE
Make VK.com plugin working on all pages

### PR DESCRIPTION
**Pull request by andrewslotin**
Use VK.com pop-up player to control the music and obtain current track info. This PR makes the plugin working on every page, not only "My Music".

### CODE REVIEW

**Comment by Stillness-2** [comment]
@andrewslotin, would you rewrite code of the trackInfo method on manner like Yandex Music strategy? So executeJavascript method should be called one time. Also will be great if you implement isPlaying method. Description of the new approach on the main page of the project. :)

**Comment by andrewslotin** [comment]
@Stillness-2, thanks for pointing me to an example, I'm mostly a cut-and-paste developer when it comes to Obj-C :smiley: Both your comments were addressed, also I made some improvements to make  interaction with the pop-up player more reliable.

**Comment by Stillness-2** [comment]
@andrewslotin, спасибо Вам за понимание! :)

**Comment by andrewslotin** [comment]
@Stillness-2, :wink:

**Pull request merged**
