### PR TITLE
Feature/issues/365

### PR DESCRIPTION
**Pull request by Stillness-2**
@1ps0 Check this please before I will merge PR in master.

### CODE REVIEW

**Comment by 1ps0** [comment]
Would you mind if we put together an official code style guide? We have a lot of mixed style and format in the project. It makes reading code much harder.

**Comment by Stillness-2** [comment]
>We have a lot of mixed style and format in the project.

 Hmm. I don't see this as a problem. I have only one rule: "don't reformat existing code to fit my format".
> It makes reading code much harder.

For me, no problem.

It's a matter of taste...

For example, I don't like what you write:
```
if (1)
{
    NSLog();
}
```
as I write:
```
if (1) {

    NSLog();
}
```
But I say nothing :) Well, there is a lot more... But I say nothing :)

You can try to describe the format for the project, of course.
Also, recently I started to use https://github.com/travisjeffery/ClangFormat-Xcode with a custom settings file:
[clang-format.zip](https://github.com/beardedspice/beardedspice/files/338210/clang-format.zip)
(`.clang-format` file inside `clang-format.zip`)

**Comment by 1ps0** [comment]
Yea its a good rule, with a few exceptions. I don't mind doing braces your way. 

Not pointing out where you've broken your own rule a bunch of times... the biggest issue I have is where single statements are newlined to fit within a column limit (?). For example...

```objc
 +    NSString *path = [[NSUserDefaults standardUserDefaults]
 +        stringForKey:BeardedSpiceImportExportLastDirectory];
 +    if (path) {...
```

Instead of newlining it (which currently is inconsistent and confusing), why not just let it run long, or break up statements into separate lines. Objective-C is verbose, sometimes we just have to accept it. :)

```objc
 +    NSBundle *bundle = [NSUserDefaults standardUserDefaults];
 +    NSString *path = [bundle stringForKey:BeardedSpiceImportExportLastDirectory];
 +    if (path) {...
```

**Comment by 1ps0** [comment]
I'm in the process of writing up the basics in a small gist, will link when I've covered what I can. 

Only real issue I have with this particular PR (formatting aside) is the deeply nested if statements that exit weirdly. There's a lot of code that can be DRY'd for readability at least (all the NSAlert stuff). Since it's your code, i'll leave that to you. 

Code works, so 👍

**Comment by Stillness-2** [comment]
```
 +    NSString *path = [[NSUserDefaults standardUserDefaults]
 +        stringForKey:BeardedSpiceImportExportLastDirectory];
```
The consequences of work of the clang-format :) Maybe I need to tweak the settings format :))

**Comment by 1ps0** [comment]
Also can you fix the formatting on StyleJukebox.js? I think thats getting messed up by ClangFormat too.

**Comment by 1ps0** [comment]
👍

**Pull request merged**
