### PR TITLE
Add track info, album art, and isPlaying for Songza

### PR DESCRIPTION
**Pull request by fmborghino**
Includes track title, artist, album art.
There is no per song favorite, Songza uses voting.

### CODE REVIEW

**Comment by fmborghino** [comment]
Let me know if you'd like any changes, happy to implement any feedback. I've been using this for a week and it seems stable.

**Comment by Stillness-2** [comment]
Please, add `isPlaying` method

**Comment by fmborghino** [comment]
Done, thanks for the feedback. I think I'll add isPlaying to SomaFM next (I didn't notice that piece of the API, sorry!)

**Comment by fmborghino** [comment]
Oh you already added isPlaying to SomaFM, thanks!

**Comment by fmborghino** [comment]
Squashed those commits into one to keep this cleaner, also rebased on your latest master.

**Comment by zjwhitehead** [comment]
Unfortunately it looks like Songza won't be around much longer :frowning: http://www.forbes.com/sites/hughmcintyre/2015/12/03/streaming-platform-songza-is-finally-closing/

**Comment by fmborghino** [comment]
Oh no! That is very disappointing :disappointed:

**Pull request merged**
