### PR TITLE
Add Amazon Alexa media strategy

### PR DESCRIPTION
**Pull request by bretmartin**
The Amazon Alexa web site has a media player to control Alexa-enabled devices. There is no favorite functionality.

### CODE REVIEW

**Comment by bretmartin** [comment]
Actually, for some of the services it connects to, there is favorite functionality. I didn't notice that before. I'll add that in if I get to it before this is (hopefully) merged, otherwise, I'll add it in a new PR.

**Comment by 1ps0** [comment]
@bretmartin For those of us without an Alexa device (despite millions sold!), testing will be the hard part. If you have a test setup I can replicate w/o a device it would help a lot :D

**Comment by bretmartin** [comment]
@1ps0 Do you have or are you willing to open a (free) Amazon.com account? I think that's required. Then you can use https://echosim.io/ to simulate an Alexa device in your browser. Let me know if you need more of a detailed walkthrough.

**Comment by bretmartin** [comment]
@1ps0 Oh, rats, I didn't realize that doesn't support media playback. Let me see if I can find another solution.

**Comment by 1ps0** [comment]
I have access to an amazon account to test with, just not a device. I'll take a look at echosim, let me know if you find anything better!

**Pull request closed without merging**
