### PR TITLE
Fixing Pandora Media Strategy

### PR DESCRIPTION
**Pull request by hoisingtonp**
Made query selector for Tuner__Controls element more generic to handle Pandora's change from a div to a span.

### CODE REVIEW

**Comment by tysonkerridge** [comment]
Ran this locally, appears to have fixed the issue, thanks. Hopefully we can get this reviewed and merged soon.

**Comment by 1ps0** [comment]
Tested it earlier, didnt have time to merge. Doing now.

**Comment by tysonkerridge** [comment]
Thanks!

**Comment by koppieesq** [comment]
If anyone else shows up here because Pandora stopped working on Chrome again, the solution is here: https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later)

**Pull request merged**
