### PR TITLE
Updated Stingray strategy to v3

### PR DESCRIPTION
**Pull request by jmcouillard**

### CODE REVIEW

**Comment by jmcouillard** [comment]
I forgot to update the version in Stingray.js....

**Comment by jmcouillard** [comment]
The website has changed again, new files added.

**Comment by 1ps0** [comment]
@jmcouillard Apologies for taking so long to properly test this (the affiliation requirement was a blocker for a while). 
It may be me, but when I play/pause through BS it pops up a menu (Add Channel, and other options), but doesn't actually trigger the play/pause action on the track. Can you validate this? It might be better to try for a more direct DOM hook instead for the future.
Thanks :)

**Comment by jmcouillard** [comment]
Hi, you were right, they changed the DOM once again. It is fixed now. Thanks !

**Comment by 1ps0** [comment]
@jmcouillard Great! Testing it now. 
In the meantime, can i nitpick a few small things?

1. Can you update the copyright year range? From `2016` to `2016-2017`
2. Can you convert the file to use spaces? It looks like right now it's all a mix, github renders tabs as 8 spaces and the javascript standard is 2. I have a [great joke picture](http://i.imgur.com/vOWAAUK.png) to illustrate how most people feel about this.

**Comment by 1ps0** [comment]
Looks good. If you can make those small corrections, I'll merge you in wherever I'm at. Thanks! and thanks for the patience :)

**Comment by jmcouillard** [comment]
I like your love of nicely done things. Here you go. Thanks!

**Comment by 1ps0** [comment]
You're good to go. Thanks again!

**Pull request merged**
