### PR TITLE
Fix UdemyStrategy and add symlink to fix broken CocoaPods

### PR DESCRIPTION
**Pull request by Coder-256**
Newer versions of Chrome break this strategy because the strategy no
longer has access to jQuery. Updated to be independent of jQuery. Xcode
seemed to want Pods.xcodeproj to be in the main project folder, so I
added a symlink.

### CODE REVIEW

**Comment by Stillness-2** [comment]
A little bit wrong :)

**Comment by Stillness-2** [comment]
Thanks for the tip :)

**Comment by Coder-256** [comment]
That works. But this version is more optimized and doesn't depend on jQuery, so you should consider still merging it.

**Comment by Stillness-2** [comment]
"Xcode
seemed to want Pods.xcodeproj to be in the main project folder, so I
added a symlink." - I don't understand :) What version of Xcode are you use?

**Comment by Coder-256** [comment]
I am using Xcode 7.1

**Pull request merged**
