### PR TITLE
Add progress track info

### PR DESCRIPTION
**Pull request by revolter**
This adds a preference to show the current progress of the media instead of the album. The artist is shown right below the title as they're closer to each other than the progress.

It currently works for Bandcamp and Youtube, so for other Media players that don't read the progress yet, the Preference is treated as being off.

### CODE REVIEW

**Comment by 1ps0** [comment]
Merging this into the 2.2.0 b2 preview.

**Comment by revolter** [comment]
Is that a branch? Because I can't find it.

**Comment by 1ps0** [comment]
@revolter Might have jumped the gun a little, sorry. I was going to make another release but I found myself short on time over the weekend and without my personal laptop :\
Probably tonight, next weekend latest.

**Comment by revolter** [comment]
I know the feeling. Let me know if you have any questions about it.

**Comment by 1ps0** [comment]
Actually, especially after having tested myself, I'm gonna go ahead and put this out there :)

**Comment by revolter** [comment]
Great! Do you have any list of example URLs for all providers?

**Pull request merged**
