### PR TITLE
Change strategy for Rhapsody to Napster to reflect their rename.

### PR DESCRIPTION
**Pull request by lolpack**
Rhapsody changed it's name and domain to Napster. Updated domain string matching and name to reflect this.

### CODE REVIEW

**Comment by easadler** [comment]
Is this 1998? @lolpack

**Comment by 1ps0** [comment]
Can you increment the version numbers please. In the strategy file itself and the versions.plist entry.

**Comment by lolpack** [comment]
@1ps0 Updated the version numbers

**Comment by 1ps0** [comment]
Just tested properly, apologies for the wait. 

You'll be able to pull down the official version via the Compatibility Updates menu option.

**Pull request merged**
