### PR TITLE
Added support for Laracasts.com

### PR DESCRIPTION
**Pull request by swwd**
I've added basic play/pause support for the PHP screencasts site Laracasts.

### CODE REVIEW

**Comment by Coder-256** [comment]
@Stillness-2 This seems valid, why has it not been accepted?

**Comment by Stillness-2** [comment]
I do not accept what i did not check

**Comment by 1ps0** [comment]
Please verify the javascript still works with the domain. Conversion to the new javascript format would also be appreciated. Thanks :)

**Comment by 1ps0** [comment]
Converted to js with [this commit](https://github.com/beardedspice/beardedspice/commit/0f63ad34b1c44f0ecb9b1544a41c2d9ac1af60a8) in the laracasts-strategy-web branch.

Will update when I'm able to test and confirm the js is still valid.

**Comment by nVitius** [comment]
This was taken care of by #660. @1ps0: can we close this one?

**Pull request closed without merging**
