### PR TITLE
Digitally Imported media strategy

### PR DESCRIPTION
**Pull request by dslysenko**
Added support for DigitallyImported, a streaming radio service for electronic music. Very straightforward as DI does not support skipping tracks.

### CODE REVIEW

**Comment by Stillness-2** [comment]
@dslysenko Can you add some improvements please? Like trackInfo and favorite methods. :)

**Comment by dslysenko** [comment]
@Stillness-2 Should favorite go to "Liking" a track or "Starring" it? I'm leaning toward starring as it seems to be more consistent with other players

**Comment by Stillness-2** [comment]
I think this https://www.dropbox.com/s/i1lkqxhvn6fq2cp/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-05%2021.23.53.png?dl=0

**Comment by dslysenko** [comment]
@Stillness-2 Sorry, misunderstood what favoriting was supposed to do--I think you're right ;)

**Comment by dslysenko** [comment]
Note - I accidentally did some other changes on this branch not knowing they would affect the pull request. Going to close and open a new one with a separate branch.

**Pull request closed without merging**
